In [1]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np
import pandas as pd
data=pd.read_csv("datasets\glass(SVM Program).csv")
data.head()
x=data.drop("Type",axis=1)
y=data['Type'].values

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [3]:
linear=svm.SVC(kernel="linear")
linear.fit(x_train,y_train)

print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.30000e+01 1.51593e+00 1.30900e+01 3.59000e+00 1.52000e+00 7.31000e+01
  6.70000e-01 7.83000e+00 0.00000e+00 0.00000e+00]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.71000e+02 1.52369e+00 1.34400e+01 0.00000e+00 1.58000e+00 7.22200e+01
  3.20000e-01 1.22400e+01 0.00000e+00 0.00000e+00]


In [4]:
print(linear.n_support_)
y_pred=linear.predict(x_test)

[1 3 2 4 3 2]


In [5]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9692307692307692


In [6]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[23  0  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  0  3  2  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]


In [7]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        25
           3       1.00      1.00      1.00         4
           5       1.00      0.60      0.75         5
           6       0.50      1.00      0.67         2
           7       1.00      1.00      1.00         6

    accuracy                           0.97        65
   macro avg       0.92      0.93      0.90        65
weighted avg       0.98      0.97      0.97        65



In [8]:
model1=SVC(kernel='sigmoid',gamma=0.76)
model2=SVC(kernel='poly',degree=3)
model3=SVC(kernel='rbf')

In [9]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [10]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [11]:
print("prediction by model1",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred3))

prediction by model1 0.38461538461538464
prediction by model2 0.9538461538461539
prediction by model3 0.8307692307692308


In [12]:
print("Sigmoid:\n"+classification_report(y_test,y_pred1))
print("Polynomial:\n"+classification_report(y_test,y_pred2))
print("RBF:\n"+classification_report(y_test,y_pred3))

Sigmoid:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        23
           2       0.38      1.00      0.56        25
           3       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         6

    accuracy                           0.38        65
   macro avg       0.06      0.17      0.09        65
weighted avg       0.15      0.38      0.21        65

Polynomial:
              precision    recall  f1-score   support

           1       0.96      1.00      0.98        23
           2       1.00      0.96      0.98        25
           3       1.00      1.00      1.00         4
           5       1.00      0.60      0.75         5
           6       0.50      1.00      0.67         2
           7       1.00      1.00      1.00         6

    accuracy                           0.95        65
  

C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\LOHITH\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu